### ISSUE TITLE
Port broken due to broken libtensorflow1 dependency

### ISSUE THREAD

**Issue by LennertVA** [huo-ju/photoprism-freebsd-port#84]
The FreeBSD port for tensorflow (https://github.com/psa/libtensorflow1-freebsd-port) appears dead and unmaintained. It cannot be built anymore as-is, which renders this photoprism port equally dead in the water.

**Comment by jan666** [comment]
There are packages available here: https://github.com/wynkenstein/libtensorflow1-freebsd-port

but the bigger problem is: Photoprism swichted to libtensorflow2 and there is no FreeBSD port of this - so you can't upgrade to the latest Photoprism using this packages.

**Comment by LennertVA** [comment]
> There are packages available here: https://github.com/wynkenstein/libtensorflow1-freebsd-port

Nice! Thanks.

> but the bigger problem is: Photoprism swichted to libtensorflow2 and there is no FreeBSD port of this - so you can't upgrade to the latest Photoprism using this packages.

Do you know which is the last photoprism release before this switch?

**Comment by jan666** [comment]
They changed it in release [250425-21ddba459](https://github.com/photoprism/photoprism/releases/tag/250425-21ddba459). So [250321-57590c48b](https://github.com/photoprism/photoprism/releases/tag/250321-57590c48b) should be the last one that works with libtensorflow1

**Comment by huo-ju** [comment]
The tensorflow is always the blocker on freebsd. IMO, the whole project should be moved to a onnxruntime based AI solution instead of tensorflow.  There are so many new image classification/retrieve models can easy run on any device.

**Comment by lapo-luchini** [comment]
There's a [PR for libtensorflow2](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=258621), but yet not ported.

**Comment by jan666** [comment]
> There's a [PR for libtensorflow2](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=258621), but yet not ported.

I already tried builing it, but without success. And its an old version...

**Comment by jan666** [comment]
I just noticed there is py-tensorflow. This also creates the libtensorflow.so.2. There is a patch to get it to version 2.13.1 here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=280234 and this patch works

**Comment by jan666** [comment]
I somehow managed to build photoprism 250426-27ec7a using the patch for py-tensorflow. 

It's hacky because I had to downgrade graft to match the tensorflow version 2.13.1 and I had to create /nonexistent. And it does not build in poudriere because of that:

```
=>> Checking for filesystem violations... done
=>> Error: Filesystem touched during build:
extra: nonexistent/.npm
```

But it looks like everything works in photoprism.

Anyone wants to test it? If yes - dont blame me when it breaks something.

**Comment by lapo-luchini** [comment]
> Anyone wants to test it? If yes - dont blame me when it breaks something.

I might, yes. But I have little time at the moment unfortunately. :(

**Comment by wynkenstein** [comment]
I've built the newest photoprism version with this changes made by jan666 and tested it. Everything seems to be working fine so far, no bugs or errors in using photoprism. I've also tested tensorflows functionality by trying to detect faces on new imported pictures, which works fine.

Thanks jan, much appreciated!

**Comment by jan666** [comment]
I managed to also build it in poudriere:

```
[...]
[00:03:49] [01] [00:00:12] Warning: ALLOW_NETWORKING_PACKAGES: Allowing full network access for www/photoprism | photoprism-g20250426
[00:06:28] [01] [00:02:51] Finished www/photoprism | photoprism-g20250426: Success
[...]
```

Here is my patch. Use at own risk

[g20250426.patch](https://github.com/user-attachments/files/21096975/g20250426.patch)

**Comment by jan666** [comment]
`py-tensorflow` has landed in the port tree - no need to patch it before building photoprism 

Here is my patch to update photoprism to g250707. Use at on risk.

```
[00:01:11] [01] [00:00:00] Building www/photoprism | photoprism-g250707
[00:01:22] [01] [00:00:11] Warning: ALLOW_NETWORKING_PACKAGES: Allowing full network access for www/photoprism | photoprism-g250707
[00:03:42] [01] [00:02:31] Finished www/photoprism | photoprism-g250707: Success
```

I switched to upstream versioning, so its g250707 instead of g20250707. I'm not sure where the 20 came from...

[250707-d28b3101e.patch](https://github.com/user-attachments/files/21115477/250707-d28b3101e.patch)

**Comment by lapo-luchini** [comment]
> I just noticed there is py-tensorflow. This also creates the libtensorflow.so.2. There is a patch to get it to version 2.13.1 here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=280234 and this patch works

Has been [committed](https://github.com/FreeBSD/freebsd-ports/commit/b3cb690e14030ee06d8e5d0737e621e0d8cebc83). 🎉

**Comment by vovkasm** [comment]
Thanks @jan666 (and all people that works on that), just finish installing it in a freebsd jail and it worked! Previous version was from someone else pkgs for tensorflow built for previous version of freebsd.
This version was fully built on my server with poudriere for 14.2-RELEASE-p4.

If anyone want packages, they are [here](https://poudriere.vovkasm.org/packages/14-2-amd64-default), but be warned, that I'm use some specific options to optimize pkgs for my needs, and not very carefully manage them (for ex some ports built with X11, some without, etc...)

**Comment by lapo-luchini** [comment]
> [00:01:11] [01] [00:00:00] Building www/photoprism | photoprism-g250707
> [00:01:22] [01] [00:00:11] Warning: ALLOW_NETWORKING_PACKAGES: Allowing full network access for www/photoprism | photoprism-g250707

Wow, nice! 🎉
Now we only need to drop need for `ALLOW_NETWORKING_PACKAGES` in order to have an official package.

**Comment by chmeeedalf** [comment]
> > I just noticed there is py-tensorflow. This also creates the libtensorflow.so.2. There is a patch to get it to version 2.13.1 here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=280234 and this patch works
> 
> Has been [committed](https://github.com/FreeBSD/freebsd-ports/commit/b3cb690e14030ee06d8e5d0737e621e0d8cebc83). 🎉

Can science/py-tensorflow be updated for aarch64 as well?  I know it (or the old dependency) used to build at least, because I'm running photoprism on a Honeycomb LX2 board.

**Comment by chmeeedalf** [comment]
I've built (via a ton of hacks) science/py-tensorflow for arm64, and when I feel inspired I'll work more on making it a viable port patch.

That said, it looks like this port needs to depend on unzip, else the models don't get packaged, and it errors.

**Comment by jan666** [comment]
Updated port for [251130-b3068414c](https://github.com/photoprism/photoprism/releases/tag/251130-b3068414c). Builds on FreeBSD 14.3 in poudriere.

Use at your own risk. I had to add some glib20 libraries, I dont know why. USE_GNOME+=glib20 did not work.

[251130-b3068414c.patch](https://github.com/user-attachments/files/23926133/251130-b3068414c.patch)

**Comment by chmeeedalf** [comment]
> Updated port for [251130-b3068414c](https://github.com/photoprism/photoprism/releases/tag/251130-b3068414c). Builds on FreeBSD 14.3 in poudriere.
> 
> Use at your own risk. I had to add some glib20 libraries, I dont know why. USE_GNOME+=glib20 did not work.
> 
> [251130-b3068414c.patch](https://github.com/user-attachments/files/23926133/251130-b3068414c.patch)

Built fine on my arm64, and works well, too.  Thanks for that quick update, @jan666 !

**Comment by lapo-luchini** [comment]
> Builds on FreeBSD 14.3 in poudriere.

If we manage to remove the necessity for `ALLOW_NETWORKING_PACKAGES` this could become an official Port. I'm not sure how to achieve that at the moment, though. 🤔

**Comment by jan666** [comment]
> If we manage to remove the necessity for `ALLOW_NETWORKING_PACKAGES` this could become an official Port. I'm not sure how to achieve that at the moment, though. 🤔

afaik you have to upload the distfiles to the freebsd distfile cache. I think the `multimedia/jellyfin` port does this, but I don't really anderstand how

**Comment by jan666** [comment]
Updated port for [260305-fad9d5395](https://github.com/photoprism/photoprism/releases/tag/260305-fad9d5395). Builds on FreeBSD 14.3 in poudriere.

[260305-fad9d5395.patch](https://github.com/user-attachments/files/25841507/260305-fad9d5395.patch)

**Comment by lapo-luchini** [comment]
I get this error: 🤔

```
var/cache/distfiles/go/www_photoprism/pkg/mod/github.com/wamuir/graft@v0.5.1/tensorflow/saved_model.go:29:11: fatal error: 'tensorflow/c/c_api.h' file not found
   29 |  #include "tensorflow/c/c_api.h"
      |           ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by jan666** [comment]
Yes, because `py-tensorflow` is too new with the latest update. And IIRC it no longer provides libtensorflow (the last version I think is 2.18).

I copied the last working version to `science/py-tensorflow213` and changed the dependency:

`LIB_DEPENDS=    libtensorflow.so.2:science/py-tensorflow213 \`

**Comment by lapo-luchini** [comment]
An easy way to re-install 2.13:
```
% cat /usr/local/etc/pkg/repos/FreeBSD.conf
FreeBSD-ports: { url: "pkg+https://pkg.FreeBSD.org/${ABI}/release_0" }
% sudo pkg install -f py311-tensorflow-2.13.1
% sudo pkg lock py311-tensorflow-2.13.1
% sudo rm /usr/local/etc/pkg/repos/FreeBSD.conf
```

**Comment by lapo-luchini** [comment]
`pkg lock` is no longer viable. :(
`May 19 14:54:49 <daemon.notice> hostname photoprism[14214]: ld-elf.so.1: Shared object "libgrpc.so.49" not f
ound, required by "libtensorflow.so.2`

**Comment by jan666** [comment]
there is a conflict. The old py-tensorflow package needs numpy1, other packages need numpy2 now. I don't know how to solve this

**Comment by lapo-luchini** [comment]
Maybe building without face recognition is a possibility in the meanwhile?
(better than not being able to even see old photos)

**Comment by lapo-luchini** [comment]
I tried [asking upstream](https://github.com/photoprism/photoprism/issues/5591).

**Comment by vovkasm** [comment]
I did a little research on alternatives, and it looks like everything PhotoPrism currently does with TensorFlow and ONNX could be done with Alibaba's MNN. I'm hoping to find some time for experiments (the two riskiest parts are converting the model weights, especially FaceNet, and the cgo wrapper for MNN). It seems to me that if this succeeds, even if PhotoPrism itself doesn't migrate to MNN, this patch might end up easier to maintain than maintaining the TensorFlow port for FreeBSD...

**Comment by lapo-luchini** [comment]
I used Claude Code to generate a [release with optional Tensorflow](https://github.com/lapo-luchini/photoprism/commit/d0b4e157a9b9c1145c979ef5c53b91d0b4b4becb), and used that to upgrade this port (#85).
